---

structure: "The ?{adjective} {noun} ?{adverb} {verb} the ?{adjective} {noun}"
words:
  verb: words/verbs.txt 
  noun: words/nouns.txt 
  adjective: words/adjectives.txt
  adverb: words/adverbs.txt

